### ISSUE TITLE
Unable to launch the sample

### ISSUE THREAD

**Issue by pcdus** [GiusepeCasagrande/RoutingSimpleSample#1]
Hello,
I would like to know if it there is something to do to launch your sample?
I can build the 3 projects without any problem (PCL, iOS, Android), but there is an error on the main page when I'm trying to deploy the app on iOS or Android:

```
public Page CreateMainPage()
{
  // NB: This returns the opening page that the platform-specific
  // boilerplate code will look for. It will know to find us because
  // we've registered our AppBootstrapper as an IScreen.
  return new RoutedViewHost();
}
```
Thank you,

**Comment by niekdegooijerfh** [comment]
got the same problem. This is what i find in the exception:
`Could not resolve type with token 0100000d (from typeref, class/assembly Xamarin.Forms.Xaml.XamlFilePathAttribute, Xamarin.Forms.Xaml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)` Tried on iOS simulator(iphone 7, iOS 10.3.1) and android nexus 5x (api lvl 25).

**Comment by GiusepeCasagrande** [comment]
Hello, 

Sorry for the delay guys. The issue you where facing is caused by fact that outdate Xamarin.Forms won't run on VS2017 and VSfM.
I have updated XF and RxUI versions. Now it's working!

Cheers, 

Giusepe

**Comment by niekdegooijerfh** [comment]
Works like a charm. gonna studie the example when i have time again. Thnx!
